name: Android Build (Release)

on:
  # Triggers the workflow on push events to the 'main' branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # Runs on the latest Ubuntu environment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      # Uses the official action to clone your repository code
      uses: actions/checkout@v4

    - name: Set up Java 17 for Android
      # Sets up the Java environment required by modern Android Gradle builds
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle' # Caches Gradle dependencies to speed up subsequent runs

    - name: Grant execute permission to gradlew
      # Ensures the Gradle wrapper script is executable
      run: chmod +x gradlew

    - name: Run Release Build (assembleRelease)
      # This command builds the unsigned release APK (app-release-unsigned.apk).
      # IMPORTANT: We pass the API Key as a Gradle property. You must configure your
      # Model.kt or BuildConfig to read the key from this property instead of hardcoding it.
      run: ./gradlew assembleRelease -PgeminiApiKey=${{ secrets.GEMINI_API_KEY }}

    - name: Upload Release APK
      # Uploads the generated APK file as a workflow artifact for easy download
      uses: actions/upload-artifact@v4
      with:
        name: gemini-chat-app-release
        path: app/build/outputs/apk/release/Gemini-UnSafe.apk
        if-no-files-found: error


